Habilitar step do sonar

diff --git a/.github/workflows/email-notification-ci-pipeline.yml b/.github/workflows/email-notification-ci-pipeline.yml
--- a/.github/workflows/email-notification-ci-pipeline.yml
+++ b/.github/workflows/email-notification-ci-pipeline.yml
@@ -3,14 +3,13 @@ name: Email Notification MS CI Pipeline
 on:
   push:
     branches:
-      - develop
       - main
       - chore/setup-pipeline
+
 env:
-  
-  #SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
-  #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-  #EKS_CLUSTER_NAME: 'ez-frame-generator-cluster-dev'
+  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  EKS_CLUSTER_NAME: 'ez-frame-generator-cluster'
   JAVA_VERSION: '21'
   DOCKER_IMAGE_NAME: 'dasilvathaynara/email-notification-ms'
   DOCKER_TAG_LATEST: 'latest'
@@ -21,7 +20,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set up JDK
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: ${{ env.JAVA_VERSION }}
@@ -31,10 +30,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set up JDK
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: ${{ env.JAVA_VERSION }}
@@ -55,42 +54,49 @@ jobs:
           name: test-report
           path: target/surefire-reports
 
-  #static-code-analysis:
-  #  needs: build-and-test
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - name: Checkout repository
-  #      uses: actions/checkout@v3
-  #
-  #    - name: Run SonarQube Scan
-  #      run: mvn clean verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
-  #
-  #    - name: Wait for SonarCloud Processing
-  #      run: sleep 10
-  #
-  #    - name: Check SonarQube Quality Gate Status
-  #      run: |
-  #        response=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}")
-  #        status=$(echo "$response" | jq -r '.projectStatus.status')
-  #
-  #        echo "Quality Gate Status: $status"
-  #
-  #        if [[ "$status" != "OK" ]]; then
-  #          echo "❌ Quality Gate failed!"
-  #          exit 1
-  #        fi
-  #
-  #    - name: ✅ SonarQube Passed
-  #      run: echo "🎉 Quality Gate Passed."
-  #
-  docker-build-push:
-    needs:
-      - build-and-test
-      #- static-code-analysis
+  static-code-analysis:
+    needs: build-and-test
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+
+      - name: Run SonarQube Scan
+        run: mvn clean verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+
+      - name: Wait for SonarCloud Processing
+        run: sleep 10
+
+      - name: Check SonarQube Quality Gate Status
+        run: |
+          response=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}")
+          status=$(echo "$response" | jq -r '.projectStatus.status')
+
+          echo "Quality Gate Status: $status"
+
+          if [[ "$status" != "OK" ]]; then
+            echo "❌ Quality Gate failed!"
+            exit 1
+          fi
+
+      - name: ✅ SonarQube Passed
+        run: echo "🎉 Quality Gate Passed."
+
+  docker-build-push:
+    needs:
+      - build-and-test
+      - static-code-analysis
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: ${{ env.JAVA_VERSION }}
+          cache: 'maven'
   
       - name: Set up Docker Build
         uses: docker/setup-buildx-action@v3
